<a href="https://colab.research.google.com/github/amritaa72/Runs-and-Wickets/blob/main/pandas_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas

In [ ]:
type(pandas)

module

In [ ]:
import pandas as pd

# **MOUNTING THE DRIVE!**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## **Read files of different format**

In [ ]:
cricket_data= pd.read_csv("/content/drive/MyDrive/Cricket_pandas/IPL_Players_20.csv")
cricket_data

,Player,Mat,Runs,HS,Bat_Avg,Balls Faced,Bat_SR,100,50,4s,6s,Overs,Runs.1,Wkts,Bowl_Avg,Econ,Bowl_SR,4w,5w
0,Subhman Gill,17,890.0,129.0,59.33,564.0,157.80,3.0,4.0,85.0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Virat Kohli,14,639.0,101.0,53.25,457.0,139.82,2.0,6.0,65.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Yashasvi Jaiswal,14,625.0,124.0,48.08,382.0,163.61,1.0,5.0,82.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SuryaKumar Yadav,16,605.0,103.0,43.21,334.0,181.13,1.0,5.0,65.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ruturaj Gaikwad,16,590.0,92.0,42.14,400.0,147.50,0.0,4.0,46.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Rinku Singh,14,474.0,67.0,59.25,317.0,149.52,0.0,4.0,31.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Sai Sudarshan,8,362.0,96.0,51.71,256.0,141.40,0.0,3.0,33.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Nicholas Pooran,15,358.0,62.0,29.83,207.0,172.94,0.0,2.0,26.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Ms Dhoni,16,104.0,32.0,26.00,57.0,182.45,0.0,0.0,3.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Andre Rusell,14,227.0,42.0,20.64,156.0,145.51,0.0,0.0,13.0,18.0,15.1,172.0,7.0,24.57,11.34,13.00,0.0,0.0
10,Shivam Dube,16,418.0,52.0,38.00,264.0,158.33,0.0,3.0,12.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Rashid Khan,17,130.0,79.0,32.50,60.0,216.66,0.0,1.0,8.0,13.0,67.0,552.0,27.0,20.44,8.23,14.88,1.0,0.0
12,Ravindra Jadeja,16,190.0,25.0,23.75,133.0,142.85,0.0,0.0,11.0,9.0,57.0,431.0,20.0,21.55,7.56,17.10,0.0,0.0
13,Glenn Maxwell,14,400.0,77.0,33.33,218.0,183.48,0.0,5.0,29.0,31.0,10.2,94.0,3.0,31.33,9.09,20.66,0.0,0.0
14,Cameron Green,16,452.0,100.0,50.22,282.0,160.28,1.0,2.0,40.0,22.0,38.0,361.0,6.0,60.16,9.50,38.00,0.0,0.0
15,Hardik Pandya,16,346.0,66.0,31.45,253.0,136.75,0.0,2.0,26.0,15.0,25.0,228.0,3.0,76.00,9.12,50.00,0.0,0.0
16,Ravichandran Ashwin,13,67.0,30.0,11.17,51.0,131.37,0.0,0.0,5.0,3.0,49.0,368.0,14.0,26.28,7.51,21.00,0.0,0.0
17,Matheesha Pathirana,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.2,371.0,19.0,19.52,8.00,14.63,0.0,0.0
18,Varun Chakravarthy,14,1.0,1.0,1.00,9.0,11.11,0.0,0.0,0.0,0.0,52.4,429.0,20.0,21.45,8.14,15.80,1.0,0.0

cric_info_excel=pd.read_excel("/content/drive/MyDrive/Cricket_pandas/IPL_Players_20.xlsx")

it reads the first sheet by default

if you want to read a specific sheet -- mention sheet name beside

cric_info_exel_2=pd.read_excel("/conetnt/drive/MyDrive/Cricket_pandas/IPL_Players_20.xlsx",sheet_name="Sheet_1")

In [ ]:
cricket_data.columns

Index(['Player', 'Mat', 'Runs', 'HS', 'Bat_Avg', 'Balls Faced', 'Bat_SR',
       '100', '50', '4s', '6s', 'Overs', 'Runs.1', 'Wkts', 'Bowl_Avg', 'Econ',
       'Bowl_SR', '4w', '5w'],
      dtype='object')

In [ ]:
cricket_data.rename(columns={"Runs.1":"Runs_delivered"},inplace=True)

In [ ]:
cricket_data.columns

Index(['Player', 'Mat', 'Runs', 'HS', 'Bat_Avg', 'Balls Faced', 'Bat_SR',
       '100', '50', '4s', '6s', 'Overs', 'Runs_delivered', 'Wkts', 'Bowl_Avg',
       'Econ', 'Bowl_SR', '4w', '5w'],
      dtype='object')

head()
Obtain first 5 values from the data frame.

In [ ]:
cricket_data.head()

,Player,Mat,Runs,HS,Bat_Avg,Balls Faced,Bat_SR,100,50,4s,6s,Overs,Runs_delivered,Wkts,Bowl_Avg,Econ,Bowl_SR,4w,5w
0,Subhman Gill,17,890.0,129.0,59.33,564.0,157.80,3.0,4.0,85.0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Virat Kohli,14,639.0,101.0,53.25,457.0,139.82,2.0,6.0,65.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Yashasvi Jaiswal,14,625.0,124.0,48.08,382.0,163.61,1.0,5.0,82.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SuryaKumar Yadav,16,605.0,103.0,43.21,334.0,181.13,1.0,5.0,65.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ruturaj Gaikwad,16,590.0,92.0,42.14,400.0,147.50,0.0,4.0,46.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

.tail() Obtain last 5 rows

In [ ]:
cricket_data.tail()

,Player,Mat,Runs,HS,Bat_Avg,Balls Faced,Bat_SR,100,50,4s,6s,Overs,Runs_delivered,Wkts,Bowl_Avg,Econ,Bowl_SR,4w,5w
14,Cameron Green,16,452.0,100.0,50.22,282.0,160.28,1.0,2.0,40.0,22.0,38.0,361.0,6.0,60.16,9.50,38.00,0.0,0.0
15,Hardik Pandya,16,346.0,66.0,31.45,253.0,136.75,0.0,2.0,26.0,15.0,25.0,228.0,3.0,76.00,9.12,50.00,0.0,0.0
16,Ravichandran Ashwin,13,67.0,30.0,11.17,51.0,131.37,0.0,0.0,5.0,3.0,49.0,368.0,14.0,26.28,7.51,21.00,0.0,0.0
17,Matheesha Pathirana,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.2,371.0,19.0,19.52,8.00,14.63,0.0,0.0
18,Varun Chakravarthy,14,1.0,1.0,1.00,9.0,11.11,0.0,0.0,0.0,0.0,52.4,429.0,20.0,21.45,8.14,15.80,1.0,0.0

.info() Gives basic information about the data frame

In [ ]:
cricket_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Player          19 non-null     object
 1   Mat             19 non-null     int64
 2   Runs            18 non-null     float64
 3   HS              18 non-null     float64
 4   Bat_Avg         18 non-null     float64
 5   Balls Faced     18 non-null     float64
 6   Bat_SR          18 non-null     float64
 7   100             18 non-null     float64
 8   50              18 non-null     float64
 9   4s              18 non-null     float64
 10  6s              18 non-null     float64
 11  Overs           9 non-null      float64
 12  Runs_delivered  9 non-null      float64
 13  Wkts            9 non-null      float64
 14  Bowl_Avg        9 non-null      float64
 15  Econ            9 non-null      float64
 16  Bowl_SR         9 non-null      float64
 17  4w              9 non-null      float64
 18  5w              9 non-null      float64
dtypes: float64(17), int64(1), object(1)
memory usage: 2.9+ KB

.shape ==>  (rows, columns)

In [ ]:
cricket_data.shape

(19, 19)

Check fro missing values in a dataframe

In [ ]:
cricket_data.isna()

,Player,Mat,Runs,HS,Bat_Avg,Balls Faced,Bat_SR,100,50,4s,6s,Overs,Runs_delivered,Wkts,Bowl_Avg,Econ,Bowl_SR,4w,5w
0,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True
5,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True
6,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True
7,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True
8,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
cricket_data.isna().sum()

Player             0
Mat                0
Runs               1
HS                 1
Bat_Avg            1
Balls Faced        1
Bat_SR             1
100                1
50                 1
4s                 1
6s                 1
Overs             10
Runs_delivered    10
Wkts              10
Bowl_Avg          10
Econ              10
Bowl_SR           10
4w                10
5w                10
dtype: int64

.describe()

Provides statistical information about the dataframe such as mean standard deviation and quartiles

In [ ]:
cricket_data.describe()

,Mat,Runs,HS,Bat_Avg,Balls Faced,Bat_SR,100,50,4s,6s,Overs,Runs_delivered,Wkts,Bowl_Avg,Econ,Bowl_SR,4w,5w
count,19.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.0
mean,14.631579,382.111111,71.000000,36.381111,244.444444,151.250556,0.444444,2.555556,32.222222,19.777778,39.988889,334.000000,13.222222,33.477778,8.721111,22.785556,0.222222,0.0
std,2.113726,235.081185,35.683247,16.222884,151.473633,40.997995,0.855585,2.064325,26.790155,10.580535,19.455876,143.305617,8.771798,20.333446,1.208009,12.677258,0.440959,0.0
min,8.000000,1.000000,1.000000,1.000000,9.000000,11.110000,0.000000,0.000000,0.000000,0.000000,10.200000,94.000000,3.000000,19.520000,7.510000,13.000000,0.000000,0.0
25%,14.000000,199.250000,44.500000,26.957500,138.750000,141.762500,0.000000,0.250000,11.250000,12.250000,25.000000,228.000000,6.000000,21.450000,8.000000,14.880000,0.000000,0.0
50%,15.000000,381.000000,72.000000,35.665000,254.500000,153.660000,0.000000,2.500000,27.500000,20.000000,46.200000,368.000000,14.000000,24.570000,8.230000,17.100000,0.000000,0.0
75%,16.000000,561.000000,99.000000,49.685000,329.750000,170.607500,0.750000,4.000000,44.500000,28.750000,52.400000,429.000000,20.000000,31.330000,9.120000,21.000000,0.000000,0.0
max,17.000000,890.000000,129.000000,59.330000,564.000000,216.660000,3.000000,6.000000,85.000000,35.000000,67.000000,552.000000,27.000000,76.000000,11.340000,50.000000,1.000000,0.0

# INDEXING AND SLICING THROUGH DATAFRAMES

.loc()

access sepcific rows or columns based on *indexing*

**print(cricket_data.loc[0:7])
prints data of each player from index 0 TO 7 (inclusive)**

In [ ]:
print(cricket_data.loc[0])

Player            Subhman Gill
Mat                         17
Runs                     890.0
HS                       129.0
Bat_Avg                  59.33
Balls Faced              564.0
Bat_SR                   157.8
100                        3.0
50                         4.0
4s                        85.0
6s                        33.0
Overs                      NaN
Runs_delivered             NaN
Wkts                       NaN
Bowl_Avg                   NaN
Econ                       NaN
Bowl_SR                    NaN
4w                         NaN
5w                         NaN
Name: 0, dtype: object

In [ ]:
cricket_data.loc[0]

Player            Subhman Gill
Mat                         17
Runs                     890.0
HS                       129.0
Bat_Avg                  59.33
Balls Faced              564.0
Bat_SR                   157.8
100                        3.0
50                         4.0
4s                        85.0
6s                        33.0
Overs                      NaN
Runs_delivered             NaN
Wkts                       NaN
Bowl_Avg                   NaN
Econ                       NaN
Bowl_SR                    NaN
4w                         NaN
5w                         NaN
Name: 0, dtype: object

In [ ]:
print(cricket_data.loc[0:6])

             Player  Mat   Runs     HS  Bat_Avg  Balls Faced  Bat_SR  100  \
0      Subhman Gill   17  890.0  129.0    59.33        564.0  157.80  3.0
1       Virat Kohli   14  639.0  101.0    53.25        457.0  139.82  2.0
2  Yashasvi Jaiswal   14  625.0  124.0    48.08        382.0  163.61  1.0
3  SuryaKumar Yadav   16  605.0  103.0    43.21        334.0  181.13  1.0
4   Ruturaj Gaikwad   16  590.0   92.0    42.14        400.0  147.50  0.0
5       Rinku Singh   14  474.0   67.0    59.25        317.0  149.52  0.0
6     Sai Sudarshan    8  362.0   96.0    51.71        256.0  141.40  0.0

    50    4s    6s  Overs  Runs_delivered  Wkts  Bowl_Avg  Econ  Bowl_SR  4w  \
0  4.0  85.0  33.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
1  6.0  65.0  16.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
2  5.0  82.0  26.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
3  5.0  65.0  28.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
4  4.0  46.0  30.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
5  4.0  31.0  29.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
6  3.0  33.0  12.0    NaN             NaN   NaN       NaN   NaN      NaN NaN

   5w
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN

In [ ]:
print(cricket_data.loc[0:7])

             Player  Mat   Runs     HS  Bat_Avg  Balls Faced  Bat_SR  100  \
0      Subhman Gill   17  890.0  129.0    59.33        564.0  157.80  3.0
1       Virat Kohli   14  639.0  101.0    53.25        457.0  139.82  2.0
2  Yashasvi Jaiswal   14  625.0  124.0    48.08        382.0  163.61  1.0
3  SuryaKumar Yadav   16  605.0  103.0    43.21        334.0  181.13  1.0
4   Ruturaj Gaikwad   16  590.0   92.0    42.14        400.0  147.50  0.0
5       Rinku Singh   14  474.0   67.0    59.25        317.0  149.52  0.0
6     Sai Sudarshan    8  362.0   96.0    51.71        256.0  141.40  0.0
7   Nicholas Pooran   15  358.0   62.0    29.83        207.0  172.94  0.0

    50    4s    6s  Overs  Runs_delivered  Wkts  Bowl_Avg  Econ  Bowl_SR  4w  \
0  4.0  85.0  33.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
1  6.0  65.0  16.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
2  5.0  82.0  26.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
3  5.0  65.0  28.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
4  4.0  46.0  30.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
5  4.0  31.0  29.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
6  3.0  33.0  12.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
7  2.0  26.0  26.0    NaN             NaN   NaN       NaN   NaN      NaN NaN

   5w
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN
7 NaN

In [ ]:
record1=cricket_data.loc[0:4,['Player','100']]
print(record1)

             Player  100
0      Subhman Gill  3.0
1       Virat Kohli  2.0
2  Yashasvi Jaiswal  1.0
3  SuryaKumar Yadav  1.0
4   Ruturaj Gaikwad  0.0

.iloc()

similar to loc() but it uses integer based indexing to access specific rowa and columns

The iloc() function takes 2 args : row indices and column indices to be selected.

In [ ]:
print(cricket_data.iloc[0:5,0:4])

             Player  Mat   Runs     HS
0      Subhman Gill   17  890.0  129.0
1       Virat Kohli   14  639.0  101.0
2  Yashasvi Jaiswal   14  625.0  124.0
3  SuryaKumar Yadav   16  605.0  103.0
4   Ruturaj Gaikwad   16  590.0   92.0

In [ ]:
cricket_data.iloc[0:5,0:4]

             Player  Mat   Runs     HS
0      Subhman Gill   17  890.0  129.0
1       Virat Kohli   14  639.0  101.0
2  Yashasvi Jaiswal   14  625.0  124.0
3  SuryaKumar Yadav   16  605.0  103.0
4   Ruturaj Gaikwad   16  590.0   92.0

In [ ]:
print(cricket_data.iloc[:,1:3])

    Mat   Runs
0    17  890.0
1    14  639.0
2    14  625.0
3    16  605.0
4    16  590.0
5    14  474.0
6     8  362.0
7    15  358.0
8    16  104.0
9    14  227.0
10   16  418.0
11   17  130.0
12   16  190.0
13   14  400.0
14   16  452.0
15   16  346.0
16   13   67.0
17   12    NaN
18   14    1.0

In [ ]:
print(cricket_data.iloc[0:5,:])

             Player  Mat   Runs     HS  Bat_Avg  Balls Faced  Bat_SR  100  \
0      Subhman Gill   17  890.0  129.0    59.33        564.0  157.80  3.0
1       Virat Kohli   14  639.0  101.0    53.25        457.0  139.82  2.0
2  Yashasvi Jaiswal   14  625.0  124.0    48.08        382.0  163.61  1.0
3  SuryaKumar Yadav   16  605.0  103.0    43.21        334.0  181.13  1.0
4   Ruturaj Gaikwad   16  590.0   92.0    42.14        400.0  147.50  0.0

    50    4s    6s  Overs  Runs_delivered  Wkts  Bowl_Avg  Econ  Bowl_SR  4w  \
0  4.0  85.0  33.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
1  6.0  65.0  16.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
2  5.0  82.0  26.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
3  5.0  65.0  28.0    NaN             NaN   NaN       NaN   NaN      NaN NaN
4  4.0  46.0  30.0    NaN             NaN   NaN       NaN   NaN      NaN NaN

   5w
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN

In [ ]:
print(cricket_data.iloc[:,])

                 Player  Mat   Runs     HS  Bat_Avg  Balls Faced  Bat_SR  100  \
0          Subhman Gill   17  890.0  129.0    59.33        564.0  157.80  3.0
1           Virat Kohli   14  639.0  101.0    53.25        457.0  139.82  2.0
2      Yashasvi Jaiswal   14  625.0  124.0    48.08        382.0  163.61  1.0
3      SuryaKumar Yadav   16  605.0  103.0    43.21        334.0  181.13  1.0
4       Ruturaj Gaikwad   16  590.0   92.0    42.14        400.0  147.50  0.0
5           Rinku Singh   14  474.0   67.0    59.25        317.0  149.52  0.0
6         Sai Sudarshan    8  362.0   96.0    51.71        256.0  141.40  0.0
7       Nicholas Pooran   15  358.0   62.0    29.83        207.0  172.94  0.0
8              Ms Dhoni   16  104.0   32.0    26.00         57.0  182.45  0.0
9          Andre Rusell   14  227.0   42.0    20.64        156.0  145.51  0.0
10          Shivam Dube   16  418.0   52.0    38.00        264.0  158.33  0.0
11          Rashid Khan   17  130.0   79.0    32.50         60.0  216.66  0.0
12     Ravindra Jadeja    16  190.0   25.0    23.75        133.0  142.85  0.0
13        Glenn Maxwell   14  400.0   77.0    33.33        218.0  183.48  0.0
14        Cameron Green   16  452.0  100.0    50.22        282.0  160.28  1.0
15        Hardik Pandya   16  346.0   66.0    31.45        253.0  136.75  0.0
16  Ravichandran Ashwin   13   67.0   30.0    11.17         51.0  131.37  0.0
17  Matheesha Pathirana   12    NaN    NaN      NaN          NaN     NaN  NaN
18   Varun Chakravarthy   14    1.0    1.0     1.00          9.0   11.11  0.0

     50    4s    6s  Overs  Runs_delivered  Wkts  Bowl_Avg   Econ  Bowl_SR  \
0   4.0  85.0  33.0    NaN             NaN   NaN       NaN    NaN      NaN
1   6.0  65.0  16.0    NaN             NaN   NaN       NaN    NaN      NaN
2   5.0  82.0  26.0    NaN             NaN   NaN       NaN    NaN      NaN
3   5.0  65.0  28.0    NaN             NaN   NaN       NaN    NaN      NaN
4   4.0  46.0  30.0    NaN             NaN   NaN       NaN    NaN      NaN
5   4.0  31.0  29.0    NaN             NaN   NaN       NaN    NaN      NaN
6   3.0  33.0  12.0    NaN             NaN   NaN       NaN    NaN      NaN
7   2.0  26.0  26.0    NaN             NaN   NaN       NaN    NaN      NaN
8   0.0   3.0  10.0    NaN             NaN   NaN       NaN    NaN      NaN
9   0.0  13.0  18.0   15.1           172.0   7.0     24.57  11.34    13.00
10  3.0  12.0  35.0    NaN             NaN   NaN       NaN    NaN      NaN
11  1.0   8.0  13.0   67.0           552.0  27.0     20.44   8.23    14.88
12  0.0  11.0   9.0   57.0           431.0  20.0     21.55   7.56    17.10
13  5.0  29.0  31.0   10.2            94.0   3.0     31.33   9.09    20.66
14  2.0  40.0  22.0   38.0           361.0   6.0     60.16   9.50    38.00
15  2.0  26.0  15.0   25.0           228.0   3.0     76.00   9.12    50.00
16  0.0   5.0   3.0   49.0           368.0  14.0     26.28   7.51    21.00
17  NaN   NaN   NaN   46.2           371.0  19.0     19.52   8.00    14.63
18  0.0   0.0   0.0   52.4           429.0  20.0     21.45   8.14    15.80

     4w   5w
0   NaN  NaN
1   NaN  NaN
2   NaN  NaN
3   NaN  NaN
4   NaN  NaN
5   NaN  NaN
6   NaN  NaN
7   NaN  NaN
8   NaN  NaN
9   0.0  0.0
10  NaN  NaN
11  1.0  0.0
12  0.0  0.0
13  0.0  0.0
14  0.0  0.0
15  0.0  0.0
16  0.0  0.0
17  0.0  0.0
18  1.0  0.0

Filtering and Querying

In [ ]:
cricket_data[cricket_data['6s']>15]

,Player,Mat,Runs,HS,Bat_Avg,Balls Faced,Bat_SR,100,50,4s,6s,Overs,Runs_delivered,Wkts,Bowl_Avg,Econ,Bowl_SR,4w,5w
0,Subhman Gill,17,890.0,129.0,59.33,564.0,157.80,3.0,4.0,85.0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Virat Kohli,14,639.0,101.0,53.25,457.0,139.82,2.0,6.0,65.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Yashasvi Jaiswal,14,625.0,124.0,48.08,382.0,163.61,1.0,5.0,82.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SuryaKumar Yadav,16,605.0,103.0,43.21,334.0,181.13,1.0,5.0,65.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ruturaj Gaikwad,16,590.0,92.0,42.14,400.0,147.50,0.0,4.0,46.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Rinku Singh,14,474.0,67.0,59.25,317.0,149.52,0.0,4.0,31.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Nicholas Pooran,15,358.0,62.0,29.83,207.0,172.94,0.0,2.0,26.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Andre Rusell,14,227.0,42.0,20.64,156.0,145.51,0.0,0.0,13.0,18.0,15.1,172.0,7.0,24.57,11.34,13.00,0.0,0.0
10,Shivam Dube,16,418.0,52.0,38.00,264.0,158.33,0.0,3.0,12.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Glenn Maxwell,14,400.0,77.0,33.33,218.0,183.48,0.0,5.0,29.0,31.0,10.2,94.0,3.0,31.33,9.09,20.66,0.0,0.0
14,Cameron Green,16,452.0,100.0,50.22,282.0,160.28,1.0,2.0,40.0,22.0,38.0,361.0,6.0,60.16,9.50,38.00,0.0,0.0

In [ ]:
filtered_cricket_data=cricket_data.query("Bat_SR>150")
filtered_cricket_data

,Player,Mat,Runs,HS,Bat_Avg,Balls Faced,Bat_SR,100,50,4s,6s,Overs,Runs_delivered,Wkts,Bowl_Avg,Econ,Bowl_SR,4w,5w
0,Subhman Gill,17,890.0,129.0,59.33,564.0,157.80,3.0,4.0,85.0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Yashasvi Jaiswal,14,625.0,124.0,48.08,382.0,163.61,1.0,5.0,82.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SuryaKumar Yadav,16,605.0,103.0,43.21,334.0,181.13,1.0,5.0,65.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Nicholas Pooran,15,358.0,62.0,29.83,207.0,172.94,0.0,2.0,26.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Ms Dhoni,16,104.0,32.0,26.00,57.0,182.45,0.0,0.0,3.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Shivam Dube,16,418.0,52.0,38.00,264.0,158.33,0.0,3.0,12.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Rashid Khan,17,130.0,79.0,32.50,60.0,216.66,0.0,1.0,8.0,13.0,67.0,552.0,27.0,20.44,8.23,14.88,1.0,0.0
13,Glenn Maxwell,14,400.0,77.0,33.33,218.0,183.48,0.0,5.0,29.0,31.0,10.2,94.0,3.0,31.33,9.09,20.66,0.0,0.0
14,Cameron Green,16,452.0,100.0,50.22,282.0,160.28,1.0,2.0,40.0,22.0,38.0,361.0,6.0,60.16,9.50,38.00,0.0,0.0

## Sorting

In [ ]:
cricket_data.sort_values('Bat_Avg')

,Player,Mat,Runs,HS,Bat_Avg,Balls Faced,Bat_SR,100,50,4s,6s,Overs,Runs_delivered,Wkts,Bowl_Avg,Econ,Bowl_SR,4w,5w
18,Varun Chakravarthy,14,1.0,1.0,1.00,9.0,11.11,0.0,0.0,0.0,0.0,52.4,429.0,20.0,21.45,8.14,15.80,1.0,0.0
16,Ravichandran Ashwin,13,67.0,30.0,11.17,51.0,131.37,0.0,0.0,5.0,3.0,49.0,368.0,14.0,26.28,7.51,21.00,0.0,0.0
9,Andre Rusell,14,227.0,42.0,20.64,156.0,145.51,0.0,0.0,13.0,18.0,15.1,172.0,7.0,24.57,11.34,13.00,0.0,0.0
12,Ravindra Jadeja,16,190.0,25.0,23.75,133.0,142.85,0.0,0.0,11.0,9.0,57.0,431.0,20.0,21.55,7.56,17.10,0.0,0.0
8,Ms Dhoni,16,104.0,32.0,26.00,57.0,182.45,0.0,0.0,3.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Nicholas Pooran,15,358.0,62.0,29.83,207.0,172.94,0.0,2.0,26.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Hardik Pandya,16,346.0,66.0,31.45,253.0,136.75,0.0,2.0,26.0,15.0,25.0,228.0,3.0,76.00,9.12,50.00,0.0,0.0
11,Rashid Khan,17,130.0,79.0,32.50,60.0,216.66,0.0,1.0,8.0,13.0,67.0,552.0,27.0,20.44,8.23,14.88,1.0,0.0
13,Glenn Maxwell,14,400.0,77.0,33.33,218.0,183.48,0.0,5.0,29.0,31.0,10.2,94.0,3.0,31.33,9.09,20.66,0.0,0.0
10,Shivam Dube,16,418.0,52.0,38.00,264.0,158.33,0.0,3.0,12.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ruturaj Gaikwad,16,590.0,92.0,42.14,400.0,147.50,0.0,4.0,46.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SuryaKumar Yadav,16,605.0,103.0,43.21,334.0,181.13,1.0,5.0,65.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Yashasvi Jaiswal,14,625.0,124.0,48.08,382.0,163.61,1.0,5.0,82.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Cameron Green,16,452.0,100.0,50.22,282.0,160.28,1.0,2.0,40.0,22.0,38.0,361.0,6.0,60.16,9.50,38.00,0.0,0.0
6,Sai Sudarshan,8,362.0,96.0,51.71,256.0,141.40,0.0,3.0,33.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Virat Kohli,14,639.0,101.0,53.25,457.0,139.82,2.0,6.0,65.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Rinku Singh,14,474.0,67.0,59.25,317.0,149.52,0.0,4.0,31.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Subhman Gill,17,890.0,129.0,59.33,564.0,157.80,3.0,4.0,85.0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Matheesha Pathirana,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.2,371.0,19.0,19.52,8.00,14.63,0.0,0.0

sort 2 columns

In [ ]:
cricket_data.sort_values(['Mat','Runs'])

,Player,Mat,Runs,HS,Bat_Avg,Balls Faced,Bat_SR,100,50,4s,6s,Overs,Runs_delivered,Wkts,Bowl_Avg,Econ,Bowl_SR,4w,5w
6,Sai Sudarshan,8,362.0,96.0,51.71,256.0,141.40,0.0,3.0,33.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Matheesha Pathirana,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.2,371.0,19.0,19.52,8.00,14.63,0.0,0.0
16,Ravichandran Ashwin,13,67.0,30.0,11.17,51.0,131.37,0.0,0.0,5.0,3.0,49.0,368.0,14.0,26.28,7.51,21.00,0.0,0.0
18,Varun Chakravarthy,14,1.0,1.0,1.00,9.0,11.11,0.0,0.0,0.0,0.0,52.4,429.0,20.0,21.45,8.14,15.80,1.0,0.0
9,Andre Rusell,14,227.0,42.0,20.64,156.0,145.51,0.0,0.0,13.0,18.0,15.1,172.0,7.0,24.57,11.34,13.00,0.0,0.0
13,Glenn Maxwell,14,400.0,77.0,33.33,218.0,183.48,0.0,5.0,29.0,31.0,10.2,94.0,3.0,31.33,9.09,20.66,0.0,0.0
5,Rinku Singh,14,474.0,67.0,59.25,317.0,149.52,0.0,4.0,31.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Yashasvi Jaiswal,14,625.0,124.0,48.08,382.0,163.61,1.0,5.0,82.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Virat Kohli,14,639.0,101.0,53.25,457.0,139.82,2.0,6.0,65.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Nicholas Pooran,15,358.0,62.0,29.83,207.0,172.94,0.0,2.0,26.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Ms Dhoni,16,104.0,32.0,26.00,57.0,182.45,0.0,0.0,3.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Ravindra Jadeja,16,190.0,25.0,23.75,133.0,142.85,0.0,0.0,11.0,9.0,57.0,431.0,20.0,21.55,7.56,17.10,0.0,0.0
15,Hardik Pandya,16,346.0,66.0,31.45,253.0,136.75,0.0,2.0,26.0,15.0,25.0,228.0,3.0,76.00,9.12,50.00,0.0,0.0
10,Shivam Dube,16,418.0,52.0,38.00,264.0,158.33,0.0,3.0,12.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Cameron Green,16,452.0,100.0,50.22,282.0,160.28,1.0,2.0,40.0,22.0,38.0,361.0,6.0,60.16,9.50,38.00,0.0,0.0
4,Ruturaj Gaikwad,16,590.0,92.0,42.14,400.0,147.50,0.0,4.0,46.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SuryaKumar Yadav,16,605.0,103.0,43.21,334.0,181.13,1.0,5.0,65.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Rashid Khan,17,130.0,79.0,32.50,60.0,216.66,0.0,1.0,8.0,13.0,67.0,552.0,27.0,20.44,8.23,14.88,1.0,0.0
0,Subhman Gill,17,890.0,129.0,59.33,564.0,157.80,3.0,4.0,85.0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

sort by descending order

In [ ]:
cricket_data.sort_values("Mat",ascending=False)

,Player,Mat,Runs,HS,Bat_Avg,Balls Faced,Bat_SR,100,50,4s,6s,Overs,Runs_delivered,Wkts,Bowl_Avg,Econ,Bowl_SR,4w,5w
0,Subhman Gill,17,890.0,129.0,59.33,564.0,157.80,3.0,4.0,85.0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Rashid Khan,17,130.0,79.0,32.50,60.0,216.66,0.0,1.0,8.0,13.0,67.0,552.0,27.0,20.44,8.23,14.88,1.0,0.0
3,SuryaKumar Yadav,16,605.0,103.0,43.21,334.0,181.13,1.0,5.0,65.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Hardik Pandya,16,346.0,66.0,31.45,253.0,136.75,0.0,2.0,26.0,15.0,25.0,228.0,3.0,76.00,9.12,50.00,0.0,0.0
14,Cameron Green,16,452.0,100.0,50.22,282.0,160.28,1.0,2.0,40.0,22.0,38.0,361.0,6.0,60.16,9.50,38.00,0.0,0.0
10,Shivam Dube,16,418.0,52.0,38.00,264.0,158.33,0.0,3.0,12.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ruturaj Gaikwad,16,590.0,92.0,42.14,400.0,147.50,0.0,4.0,46.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Ravindra Jadeja,16,190.0,25.0,23.75,133.0,142.85,0.0,0.0,11.0,9.0,57.0,431.0,20.0,21.55,7.56,17.10,0.0,0.0
8,Ms Dhoni,16,104.0,32.0,26.00,57.0,182.45,0.0,0.0,3.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Nicholas Pooran,15,358.0,62.0,29.83,207.0,172.94,0.0,2.0,26.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Virat Kohli,14,639.0,101.0,53.25,457.0,139.82,2.0,6.0,65.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Yashasvi Jaiswal,14,625.0,124.0,48.08,382.0,163.61,1.0,5.0,82.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Glenn Maxwell,14,400.0,77.0,33.33,218.0,183.48,0.0,5.0,29.0,31.0,10.2,94.0,3.0,31.33,9.09,20.66,0.0,0.0
5,Rinku Singh,14,474.0,67.0,59.25,317.0,149.52,0.0,4.0,31.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Andre Rusell,14,227.0,42.0,20.64,156.0,145.51,0.0,0.0,13.0,18.0,15.1,172.0,7.0,24.57,11.34,13.00,0.0,0.0
18,Varun Chakravarthy,14,1.0,1.0,1.00,9.0,11.11,0.0,0.0,0.0,0.0,52.4,429.0,20.0,21.45,8.14,15.80,1.0,0.0
16,Ravichandran Ashwin,13,67.0,30.0,11.17,51.0,131.37,0.0,0.0,5.0,3.0,49.0,368.0,14.0,26.28,7.51,21.00,0.0,0.0
17,Matheesha Pathirana,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.2,371.0,19.0,19.52,8.00,14.63,0.0,0.0
6,Sai Sudarshan,8,362.0,96.0,51.71,256.0,141.40,0.0,3.0,33.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

concat()

used to concatenate multiple dataframes

In [ ]:
df1= pd.DataFrame({'Player':['SuryaKumar Yadav','Rohit Sharma','Jasprit Bumrah'],'Team': ['MI','MI','MI'],'Runs':[11867,9115,0],'Wickets':[0,0,97]})

In [ ]:
df2=pd.DataFrame({'Player':['Virat Kohli','Faf Duplesis','Maxwell'],'Team':['RCB','RCB','RCB'],'Runs':[10115,9115,10767]})

In [ ]:
df3=pd.DataFrame({'Player':['Ashwin','Siraj','Varun Chakravarthy'],'Team':['RR','RCB','KKR'],'Wickets':[101,91,107]})

now concatenating the dataframes

In [ ]:
concatenated_df=pd.concat([df1,df2,df3])
print(concatenated_df)

               Player Team     Runs  Wickets
0    SuryaKumar Yadav   MI  11867.0      0.0
1        Rohit Sharma   MI   9115.0      0.0
2      Jasprit Bumrah   MI      0.0     97.0
0         Virat Kohli  RCB  10115.0      NaN
1        Faf Duplesis  RCB   9115.0      NaN
2             Maxwell  RCB  10767.0      NaN
0              Ashwin   RR      NaN    101.0
1               Siraj  RCB      NaN     91.0
2  Varun Chakravarthy  KKR      NaN    107.0

merge()

combine 2 or more data frames based on a common column

In [ ]:
df4=pd.DataFrame({'Player':['MS Dhoni','Rahane','Ruturaj'],'Team':['CSK','CSK','CSK'],'Runs':[11867,9115,27]})

In [ ]:
df5=pd.DataFrame({'Player':['MS Dhoni','Rahane','Kohli'],'Team':['CSK','CSK','RCB'],'Average':[59.33,48.55,54.17]})

In [ ]:
merged_df=pd.merge(df4,df5,on='Player')
print(merged_df)

     Player Team_x   Runs Team_y  Average
0  MS Dhoni    CSK  11867    CSK    59.33
1    Rahane    CSK   9115    CSK    48.55

InnerJoin()

Combines only the maching rows frok two DataFrames based on common column.

In [ ]:
innerjoin_df=pd.merge(df4,df5, on='Player',how='inner')
print(innerjoin_df)

     Player Team_x   Runs Team_y  Average
0  MS Dhoni    CSK  11867    CSK    59.33
1    Rahane    CSK   9115    CSK    48.55

outer join

Retuns all rows from both data frames and fills missing values wth NaN for any non matching rows

In [ ]:
print(df4)
print('\n')
print(df5)
print('\n')
outerjoindf= pd.merge(df4,df5,on='Player',how='outer')
outerjoindf

     Player Team   Runs
0  MS Dhoni  CSK  11867
1    Rahane  CSK   9115
2   Ruturaj  CSK     27


     Player Team  Average
0  MS Dhoni  CSK    59.33
1    Rahane  CSK    48.55
2     Kohli  RCB    54.17

     Player Team_x     Runs Team_y  Average
0     Kohli    NaN      NaN    RCB    54.17
1  MS Dhoni    CSK  11867.0    CSK    59.33
2    Rahane    CSK   9115.0    CSK    48.55
3   Ruturaj    CSK     27.0    NaN      NaN

leftjoin()

Returns all rows from the left dataframe and the matching rows from the right dataframe

If there is no matching row in the right dataframe , the missing values are filled wih NaN

In [ ]:
print(df4)
print('\n')
print(df5)
print('\n')
leftjoindf=pd.merge(df4,df5,on='Player',how='left')
print(leftjoindf)

     Player Team   Runs
0  MS Dhoni  CSK  11867
1    Rahane  CSK   9115
2   Ruturaj  CSK     27


     Player Team  Average
0  MS Dhoni  CSK    59.33
1    Rahane  CSK    48.55
2     Kohli  RCB    54.17


     Player Team_x   Runs Team_y  Average
0  MS Dhoni    CSK  11867    CSK    59.33
1    Rahane    CSK   9115    CSK    48.55
2   Ruturaj    CSK     27    NaN      NaN

right join

returns all the rows from the right dataframe and the matching rows from the left dataframe.

If there is no matching row in the left dataframe, missing values are filled with NaN.

In [ ]:
print(df4)
print('\n')
print(df5)
print('\n')
rightjoindf=pd.merge(df4,df5, on='Player',how='right')
rightjoindf

     Player Team   Runs
0  MS Dhoni  CSK  11867
1    Rahane  CSK   9115
2   Ruturaj  CSK     27


     Player Team  Average
0  MS Dhoni  CSK    59.33
1    Rahane  CSK    48.55
2     Kohli  RCB    54.17

     Player Team_x     Runs Team_y  Average
0  MS Dhoni    CSK  11867.0    CSK    59.33
1    Rahane    CSK   9115.0    CSK    48.55
2     Kohli    NaN      NaN    RCB    54.17

find players having minimum and maximum batting average

In [ ]:
cricket_data.Bat_Avg.max()

59.33

In [ ]:
cricket_data.Bat_Avg.min()

1.0

now get playe who got the respective score

In [ ]:
cricket_data[cricket_data['Bat_Avg']==cricket_data.Bat_Avg.max()]

,Player,Mat,Runs,HS,Bat_Avg,Balls Faced,Bat_SR,100,50,4s,6s,Overs,Runs_delivered,Wkts,Bowl_Avg,Econ,Bowl_SR,4w,5w
0,Subhman Gill,17,890.0,129.0,59.33,564.0,157.8,3.0,4.0,85.0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
cricket_data[cricket_data['Bat_Avg']==cricket_data.Bat_Avg.min()]

,Player,Mat,Runs,HS,Bat_Avg,Balls Faced,Bat_SR,100,50,4s,6s,Overs,Runs_delivered,Wkts,Bowl_Avg,Econ,Bowl_SR,4w,5w
18,Varun Chakravarthy,14,1.0,1.0,1.0,9.0,11.11,0.0,0.0,0.0,0.0,52.4,429.0,20.0,21.45,8.14,15.8,1.0,0.0

player who has max sixes

In [ ]:
cricket_data.sort_values(['6s'],ascending=False).iloc[0]

Player            Shivam Dube
Mat                        16
Runs                    418.0
HS                       52.0
Bat_Avg                  38.0
Balls Faced             264.0
Bat_SR                 158.33
100                       0.0
50                        3.0
4s                       12.0
6s                       35.0
Overs                     NaN
Runs_delivered            NaN
Wkts                      NaN
Bowl_Avg                  NaN
Econ                      NaN
Bowl_SR                   NaN
4w                        NaN
5w                        NaN
Name: 10, dtype: object

best strike rate

In [ ]:
(cricket_data.sort_values(['Bat_SR'], ascending=False).iloc[0,:])

Player            Rashid Khan
Mat                        17
Runs                    130.0
HS                       79.0
Bat_Avg                  32.5
Balls Faced              60.0
Bat_SR                 216.66
100                       0.0
50                        1.0
4s                        8.0
6s                       13.0
Overs                    67.0
Runs_delivered          552.0
Wkts                     27.0
Bowl_Avg                20.44
Econ                     8.23
Bowl_SR                 14.88
4w                        1.0
5w                        0.0
Name: 11, dtype: object